"""
Layer-by-Layer RL Training Script for GO-MELT Power Control

This script implements layer-by-layer RL training where:
1. RL generates G-code for one layer with power commands
2. Layer is executed through simulation
3. Results are observed
4. Model is updated
5. Next layer is generated with updated powers
"""

import os
import sys
import json
import argparse
import numpy as np
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import time
import tempfile
import shutil

# Add go_melt to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'go_melt'))

try:
    from stable_baselines3 import PPO, SAC, TD3
    from stable_baselines3.common.callbacks import BaseCallback
    from stable_baselines3.common.monitor import Monitor
    HAS_SB3 = True
except ImportError:
    HAS_SB3 = False
    print("Warning: stable-baselines3 not installed. Install with: pip install stable-baselines3[extra]")

from go_melt_env import GoMeltEnv
from go_melt import go_melt
from controller import get_max_temperature_level3


class LayerExecutionEnv(GoMeltEnv):
    """
    Extended environment that can be updated with real simulation results.
    """
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.real_temperatures = []
        self.real_powers = []
        self.use_real_results = False
    
    def update_with_real_results(self, temperature: float, power: float):
        """Update environment state with real simulation results."""
        self.real_temperatures.append(temperature)
        self.real_powers.append(power)
        # Update internal temperature state to match real result
        if hasattr(self, '_current_temp'):
            # Blend real result with current state for smooth transition
            self._current_temp = 0.7 * self._current_temp + 0.3 * temperature
        else:
            self._current_temp = temperature
    
    def reset_real_results(self):
        """Reset real results tracking."""
        self.real_temperatures = []
        self.real_powers = []


def generate_layer_gcode(
    layer_num: int,
    z_height: float,
    path_points: List[Tuple[float, float]],
    powers: List[float],
    output_file: str
) -> str:
    """
    Generate G-code for a single layer with RL-determined powers.
    
    Parameters:
    -----------
    layer_num : int
        Layer number (for reference)
    z_height : float
        Z height for this layer
    path_points : List[Tuple[float, float]]
        List of (x, y) coordinates for the path
    powers : List[float]
        List of power values (one per segment or point)
    output_file : str
        Path to output G-code file
        
    Returns:
    --------
    str
        Path to generated G-code file
    """
    with open(output_file, 'w') as f:
        # Write header comment
        f.write(f"; Layer {layer_num} - Generated by RL\n")
        
        # Rapid move to start position at layer height
        if len(path_points) > 0:
            x0, y0 = path_points[0]
            f.write(f"G0 X{x0:.3f} Y{y0:.3f} Z{z_height:.3f}\n")
            
            # Set initial power
            if len(powers) > 0:
                f.write(f"S{powers[0]:.1f}\n")
            
            # Generate path with power commands
            current_power = powers[0] if len(powers) > 0 else 285.0
            
            for i, (x, y) in enumerate(path_points[1:], 1):
                # Check if power should change
                power_idx = min(i, len(powers) - 1) if len(powers) > 0 else 0
                new_power = powers[power_idx] if len(powers) > power_idx else current_power
                
                # Write power command if it changed
                if abs(new_power - current_power) > 0.1:  # Only write if significant change
                    f.write(f"S{new_power:.1f}\n")
                    current_power = new_power
                
                # Write movement command
                f.write(f"G1 X{x:.3f} Y{y:.3f} Z{z_height:.3f}\n")
    
    return output_file


def extract_layer_path_from_gcode(gcode_file: str) -> List[Tuple[float, float, float]]:
    """
    Extract path points from existing G-code file.
    Returns list of (x, y, z) coordinates grouped by layer (z value).
    """
    import re
    
    with open(gcode_file, 'r') as f:
        lines = f.readlines()
    
    points = []
    current_z = None
    
    for line in lines:
        # Skip comments
        if line.strip().startswith(';'):
            continue
        
        # Match G0/G1 commands with coordinates
        match = re.search(
            r"G[01]\s+X(-?\d+\.?\d*)\s+Y(-?\d+\.?\d*)(?:\s+Z(-?\d+\.?\d*))?",
            line,
            re.IGNORECASE
        )
        if match:
            x = float(match.group(1))
            y = float(match.group(2))
            z = float(match.group(3)) if match.group(3) else current_z
            if z is not None:
                current_z = z
                points.append((x, y, z))
    
    return points


def get_layer_path_points(
    base_gcode_file: Optional[str] = None,
    layer_num: int = 0,
    default_path: Optional[List[Tuple[float, float]]] = None
) -> List[Tuple[float, float]]:
    """
    Get path points for a layer.
    
    If base_gcode_file is provided, extract from it.
    Otherwise, use default_path or create a simple path.
    """
    if base_gcode_file and os.path.exists(base_gcode_file):
        # Extract points from base G-code, filter by layer
        all_points = extract_layer_path_from_gcode(base_gcode_file)
        if all_points:
            # Group by Z height to find layer
            z_heights = sorted(set(p[2] for p in all_points if p[2] is not None))
            if layer_num < len(z_heights):
                target_z = z_heights[layer_num]
                layer_points = [p for p in all_points if p[2] is not None and abs(p[2] - target_z) < 0.001]
                if layer_points:
                    return [(p[0], p[1]) for p in layer_points]
    
    # Use default path or create simple one
    if default_path:
        return default_path
    
    # Default: simple back-and-forth path
    return [
        (2.0, 2.0),
        (8.0, 2.0),
        (2.0, 2.0),
        (8.0, 2.0)
    ]


def run_single_layer_and_observe(
    config: Dict,
    layer_gcode_file: str,
    layer_num: int,
    output_dir: str,
    target_temperature: float = 3000.0
) -> Tuple[float, List[float], List[float], float]:
    """
    Run a single layer through the simulation and observe results.
    
    Parameters:
    -----------
    config : Dict
        GO-MELT configuration dictionary
    layer_gcode_file : str
        Path to G-code file for this layer
    layer_num : int
        Layer number
    output_dir : str
        Output directory for simulation results
    target_temperature : float
        Target temperature for reward calculation
        
    Returns:
    --------
    Tuple[float, List[float], List[float], float]
        - Average temperature during layer
        - List of temperatures observed
        - List of powers used
        - Average reward
    """
    # Create a temporary config for this layer
    layer_config = json.loads(json.dumps(config))  # Deep copy
    layer_config["nonmesh"] = config["nonmesh"].copy()
    layer_config["nonmesh"]["gcode"] = layer_gcode_file
    layer_config["nonmesh"]["save_path"] = os.path.join(output_dir, f"layer_{layer_num}")
    layer_config["nonmesh"]["layer_num"] = layer_num
    
    # Disable power controller for layer execution (we're using G-code powers)
    if "power_controller" in layer_config:
        layer_config["power_controller"]["type"] = "none"
    
    # Track observations during simulation
    # We'll use a callback or modify go_melt to return observations
    # For now, we'll run and then load results
    
    temperatures = []
    powers = []
    rewards = []
    
    try:
        # Run simulation - this will execute the layer
        # Note: In a full implementation, you'd want to modify go_melt to return
        # observations during execution, or use a callback mechanism
        go_melt(layer_config)
        
        # Try to load temperature from saved results
        result_dir = Path(layer_config["nonmesh"]["save_path"])
        temp_file = result_dir / "FinalTemperatureFields.npz"
        
        if temp_file.exists():
            import jax.numpy as jnp
            data = jnp.load(str(temp_file))
            if "L3T" in data:
                max_temp = float(jnp.max(data["L3T"]))
                temperatures.append(max_temp)
            else:
                temperatures.append(3000.0)  # Default
        else:
            # If results not available, use default
            temperatures.append(3000.0)
        
        # Calculate reward based on temperature
        avg_temp = np.mean(temperatures) if temperatures else 3000.0
        error = target_temperature - avg_temp
        normalized_error = error / target_temperature
        reward = -0.1 * (normalized_error ** 2)
        reward = np.clip(reward, -100.0, 0.0)
        rewards.append(reward)
        
        return avg_temp, temperatures, powers, np.mean(rewards) if rewards else 0.0
        
    except Exception as e:
        print(f"Error running layer {layer_num}: {e}")
        import traceback
        traceback.print_exc()
        # Return default values on error
        return 3000.0, [3000.0], [], 0.0


class LayerByLayerCallback(BaseCallback):
    """Callback for layer-by-layer training."""
    
    def __init__(self, verbose=0):
        super().__init__(verbose)
        self.layer_rewards = []
        self.layer_temperatures = []
    
    def _on_step(self) -> bool:
        return True


def train_layer_by_layer(
    config_file: str,
    output_dir: str,
    algorithm: str = "PPO",
    total_layers: int = 10,
    steps_per_layer: int = 100,
    device_id: int = 0,
    **env_kwargs
):
    """
    Train RL agent layer-by-layer.
    
    Parameters:
    -----------
    config_file : str
        Path to base configuration JSON file
    output_dir : str
        Directory to save training results
    algorithm : str
        RL algorithm: "PPO", "SAC", or "TD3"
    total_layers : int
        Total number of layers to train on
    steps_per_layer : int
        Number of RL steps per layer
    device_id : int
        GPU device ID
    **env_kwargs
        Additional environment arguments
    """
    if not HAS_SB3:
        raise ImportError("stable-baselines3 is required. Install with: pip install stable-baselines3[extra]")
    
    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Load base configuration
    with open(config_file, 'r') as f:
        base_config = json.load(f)
    
    # Get layer height
    layer_height = base_config.get("properties", {}).get("layer_height", 0.04)
    
    # Get base G-code file if exists
    base_gcode = base_config.get("nonmesh", {}).get("gcode", None)
    
    # Create temporary directory for layer G-code files
    temp_dir = output_path / "layer_gcodes"
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    # Create environment for RL training
    # Use extended environment that can accept real simulation results
    def make_env():
        env = LayerExecutionEnv(
            config_file=config_file,
            device_id=device_id,
            **env_kwargs
        )
        return env
    
    env = make_env()
    
    # Select algorithm
    algorithm = algorithm.upper()
    use_device = "cpu" if algorithm == "PPO" else (f"cuda:{device_id}" if device_id >= 0 else "cpu")
    
    if algorithm == "PPO":
        model = PPO(
            "MlpPolicy",
            env,
            verbose=1,
            tensorboard_log=str(output_path / "tensorboard"),
            device=use_device,
            learning_rate=1e-4,
            n_steps=steps_per_layer,
            batch_size=64,
            n_epochs=10,
            gamma=0.99,
            gae_lambda=0.95,
            clip_range=0.2,
            ent_coef=0.01,
            max_grad_norm=0.5,
            vf_coef=0.5,
        )
    elif algorithm == "SAC":
        model = SAC(
            "MlpPolicy",
            env,
            verbose=1,
            tensorboard_log=str(output_path / "tensorboard"),
            device=use_device,
            learning_rate=3e-4,
            buffer_size=100000,
            learning_starts=1000,
            batch_size=256,
            tau=0.005,
            gamma=0.99,
            train_freq=1,
            gradient_steps=1,
        )
    elif algorithm == "TD3":
        model = TD3(
            "MlpPolicy",
            env,
            verbose=1,
            tensorboard_log=str(output_path / "tensorboard"),
            device=use_device,
            learning_rate=3e-4,
            buffer_size=100000,
            learning_starts=1000,
            batch_size=256,
            tau=0.005,
            gamma=0.99,
            train_freq=1,
            policy_delay=2,
        )
    else:
        raise ValueError(f"Unknown algorithm: {algorithm}")
    
    print(f"\nStarting layer-by-layer training with {algorithm}")
    print(f"Total layers: {total_layers}")
    print(f"Steps per layer: {steps_per_layer}")
    
    # Training loop: layer by layer
    all_layer_rewards = []
    all_layer_temperatures = []
    
    for layer_num in range(total_layers):
        print(f"\n{'='*60}")
        print(f"Training Layer {layer_num + 1}/{total_layers}")
        print(f"{'='*60}")
        
        # Get path points for this layer
        z_height = layer_num * layer_height
        path_points = get_layer_path_points(base_gcode, layer_num)
        
        # Generate powers for this layer using RL
        # Reset environment
        obs, info = env.reset()
        
        # Collect observations and actions for this layer
        layer_observations = []
        layer_actions = []
        layer_rewards = []
        layer_powers = []
        
        # Generate powers step by step
        for step in range(steps_per_layer):
            # Get action from RL model
            action, _ = model.predict(obs, deterministic=False)
            
            # Convert action to power
            # Action is normalized [-1, 1], convert to power range
            power_min = env_kwargs.get("power_min", 0.0)
            power_max = env_kwargs.get("power_max", 500.0)
            base_power = env_kwargs.get("base_power", 285.0)
            
            # Map action to power adjustment
            power_range = power_max - power_min
            power_adjustment = float(action[0]) * power_range * 0.2
            new_power = base_power + power_adjustment
            new_power = np.clip(new_power, power_min, power_max)
            layer_powers.append(new_power)
            
            # Step environment (simulated)
            obs, reward, terminated, truncated, info = env.step(action)
            
            layer_observations.append(obs.copy())
            layer_actions.append(action.copy())
            layer_rewards.append(reward)
            
            if terminated or truncated:
                obs, info = env.reset()
        
        # Generate G-code for this layer with RL-determined powers
        # Use powers at regular intervals along the path
        num_power_points = min(len(layer_powers), len(path_points))
        if num_power_points > 0:
            # Distribute powers along path
            power_indices = np.linspace(0, len(layer_powers) - 1, num_power_points, dtype=int)
            layer_powers_for_gcode = [layer_powers[i] for i in power_indices]
        else:
            layer_powers_for_gcode = [285.0] * len(path_points)
        
        layer_gcode_file = str(temp_dir / f"layer_{layer_num}.gcode")
        generate_layer_gcode(
            layer_num=layer_num,
            z_height=z_height,
            path_points=path_points,
            powers=layer_powers_for_gcode,
            output_file=layer_gcode_file
        )
        
        print(f"Generated G-code for layer {layer_num} with {len(layer_powers_for_gcode)} power points")
        print(f"Power range: {min(layer_powers_for_gcode):.1f} - {max(layer_powers_for_gcode):.1f} W")
        
        # Run the layer through simulation
        print(f"Running layer {layer_num} through simulation...")
        target_temp = env_kwargs.get("target_temperature", 3000.0)
        avg_temp, temp_history, power_history, avg_reward = run_single_layer_and_observe(
            config=base_config,
            layer_gcode_file=layer_gcode_file,
            layer_num=layer_num,
            output_dir=str(output_path),
            target_temperature=target_temp
        )
        
        # Update environment with real results for next layer
        if isinstance(env, LayerExecutionEnv):
            env.update_with_real_results(avg_temp, np.mean(layer_powers) if layer_powers else 285.0)
        
        all_layer_temperatures.append(avg_temp)
        # Use the reward from actual simulation if available, otherwise use RL reward
        if avg_reward != 0.0:
            all_layer_rewards.append(avg_reward)
        else:
            all_layer_rewards.append(np.mean(layer_rewards))
        
        print(f"Layer {layer_num} completed:")
        print(f"  Average temperature: {avg_temp:.2f} K (target: {target_temp:.2f} K)")
        print(f"  Temperature error: {abs(target_temp - avg_temp):.2f} K")
        print(f"  Average reward: {all_layer_rewards[-1]:.4f}")
        
        # Update model periodically based on accumulated experience
        # For PPO, learning happens automatically when n_steps is reached
        # We can also manually trigger learning if needed
        
        # Update RL model with collected experience from this layer
        # The model has already collected experience through env.step() calls
        # For PPO, we need to call learn() to update the policy
        if len(layer_observations) > 0 and algorithm == "PPO":
            # PPO learns in batches, so we need to accumulate enough steps
            # The model's internal buffer should have the experience
            # We can trigger learning by calling learn() with a small number of timesteps
            # or let it accumulate over multiple layers
            
            # For now, we'll learn every few layers or when we have enough steps
            # PPO typically needs n_steps (2048) before learning
            # So we accumulate steps across layers
            
            # Save checkpoint periodically
            if (layer_num + 1) % 5 == 0:
                checkpoint_path = output_path / "checkpoints" / f"model_layer_{layer_num + 1}"
                checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
                model.save(str(checkpoint_path))
                print(f"Saved checkpoint: {checkpoint_path}")
                
                # Also trigger learning if we have enough accumulated steps
                # PPO's n_steps is 2048, so we learn every ~20 layers (100 steps/layer)
                if (layer_num + 1) >= 20:
                    print(f"Triggering model update after {layer_num + 1} layers...")
                    # The model will learn on its accumulated buffer
                    # We can't directly control this with PPO, but it happens automatically
                    # when we call learn() or when n_steps is reached
    
    # Save final model
    final_model_path = output_path / "final_model"
    model.save(str(final_model_path))
    print(f"\nFinal model saved to: {final_model_path}")
    
    # Save training summary
    training_summary = {
        "algorithm": algorithm,
        "total_layers": total_layers,
        "steps_per_layer": steps_per_layer,
        "layer_rewards": all_layer_rewards,
        "layer_temperatures": all_layer_temperatures,
        "config_file": config_file
    }
    
    with open(output_path / "training_summary.json", 'w') as f:
        json.dump(training_summary, f, indent=2)
    
    print(f"\nTraining complete! Results saved to: {output_dir}")
    
    return model


def main():
    parser = argparse.ArgumentParser(
        description="Train RL agent layer-by-layer for GO-MELT power control"
    )
    parser.add_argument(
        "config_file",
        type=str,
        help="Path to GO-MELT configuration JSON file"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./rl_training_layer_by_layer",
        help="Output directory for training results"
    )
    parser.add_argument(
        "--algorithm",
        type=str,
        choices=["PPO", "SAC", "TD3"],
        default="PPO",
        help="RL algorithm to use (default: PPO)"
    )
    parser.add_argument(
        "--total-layers",
        type=int,
        default=10,
        help="Total number of layers to train on (default: 10)"
    )
    parser.add_argument(
        "--steps-per-layer",
        type=int,
        default=100,
        help="Number of RL steps per layer (default: 100)"
    )
    parser.add_argument(
        "--device-id",
        type=int,
        default=0,
        help="GPU device ID (default: 0, use -1 for CPU)"
    )
    parser.add_argument(
        "--target-temp",
        type=float,
        default=3000.0,
        help="Target temperature in Kelvin (default: 3000.0)"
    )
    parser.add_argument(
        "--power-min",
        type=float,
        default=0.0,
        help="Minimum power in Watts (default: 0.0)"
    )
    parser.add_argument(
        "--power-max",
        type=float,
        default=500.0,
        help="Maximum power in Watts (default: 500.0)"
    )
    parser.add_argument(
        "--base-power",
        type=float,
        default=285.0,
        help="Base power in Watts (default: 285.0)"
    )
    
    args = parser.parse_args()
    
    if not os.path.exists(args.config_file):
        print(f"Error: Configuration file not found: {args.config_file}")
        sys.exit(1)
    
    if args.device_id >= 0:
        os.environ["CUDA_VISIBLE_DEVICES"] = str(args.device_id)
    
    try:
        model = train_layer_by_layer(
            config_file=args.config_file,
            output_dir=args.output_dir,
            algorithm=args.algorithm,
            total_layers=args.total_layers,
            steps_per_layer=args.steps_per_layer,
            device_id=args.device_id,
            target_temperature=args.target_temp,
            power_min=args.power_min,
            power_max=args.power_max,
            base_power=args.base_power
        )
        print("\n✓ Training completed successfully!")
    except Exception as e:
        print(f"\n✗ Training failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()

